name: bmnav
description: A Flutter implementation of the Bottom Navigation Bar with no labels.
version: 0.1.0
author: Edwin Jose <edwnjos99@gmail.com>
homepage: https://github.com/edwnjos/bmnav

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter